package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    private JoinPredicate joinP;
    private DbIterator child1;
    private DbIterator child2;
    private Boolean getNextChild1 = true;
    private Tuple t1 = null;
    private Boolean keepGoing = true;
   

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        // some code goes here
    	this.joinP = p;
    	this.child1 = child1;
    	this.child2 = child2;
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return joinP;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
    	String name1 = child1.getTupleDesc().getFieldName(joinP.getField1());
        return name1;
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
    	String name2 = child2.getTupleDesc().getFieldName(joinP.getField2());
        return name2;
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
    	TupleDesc td1 = child1.getTupleDesc();
    	TupleDesc td2 = child2.getTupleDesc();
    	TupleDesc merge = TupleDesc.merge(td1, td2);
        return merge;
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
    	child1.open();
    	child2.open();
    	super.open();
    }

    public void close() {
        // some code goes here
    	child1.close();
    	child2.close();
    	super.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
    	child1.rewind();
    	child2.rewind();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
    	if (getNextChild1)
    		keepGoing = child1.hasNext();
    	while (keepGoing)
    	{
    		if (getNextChild1)
    			t1 = child1.next();
    		System.out.println("loop1");
    		
    		System.out.println(t1);
    		while (child2.hasNext())
    		{
    			System.out.println("loop2");
    			Tuple t2 = child2.next();
    			System.out.println(t2);
    			if (joinP.filter(t1, t2))
    			{
    				getNextChild1 = false;
    				Tuple joined = new Tuple(this.getTupleDesc());
    				int counter = 0;
    				for (int i = 0; i < t1.getTupleDesc().numFields(); i++)
    				{
    					joined.setField(i, t1.getField(i));
    					counter++;
    				}
    				for (int j = counter; j < joined.getTupleDesc().numFields(); j++)
    					joined.setField(j, t2.getField(j - counter));
    				System.out.println("matched tuples");
    				System.out.println(joined);
    			
    				return joined;
    				
    			}
    		}
    		
    		child2.rewind();
    		keepGoing = child1.hasNext();
    		getNextChild1 = true;
    		
    		
    	}
    	return null;
    }
    	

    @Override
    public DbIterator[] getChildren() {
        // some code goes here
        return new DbIterator[] {this.child1, this.child2};
    }

    @Override
    public void setChildren(DbIterator[] children) {
        // some code goes here
    	child1 = children[0];
    	child2 = children[1];
    }

}
